deployment:
  tasks:
    - export DEPLOYPATH=/home/kkaugcih/public_html
    - export REPOPATH=/home/kkaugcih/repositories/GarageWeb
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp User-auth.php $DEPLOYPATH
    - /bin/cp User-functions.php $DEPLOYPATH
    - /bin/find -type f -maxdepth 2 -exec /bin/cp {} $DEPLOYPATH \;