deployment:
  tasks:
    - export DEPLOYPATH=/home/kkaugcih/public_html
    - export REPOPATH=/home/kkaugcih/repositories/GarageWeb
    - /bin/cp index.php $DEPLOYPATH
    # - /bin/cp Front-end/*.html $DEPLOYPATH
    # - /bin/cp Front-end/*.css $DEPLOYPATH
    # - /bin/cp -r Front-end/Photos/. $DEPLOYPATH/Photos/
    # - /bin/cp -r Front-end/SvgFiles/. $DEPLOYPATH/SvgFiles/
    - /bin/cp User-auth.php $DEPLOYPATH
    - /bin/cp User-functions.php $DEPLOYPATH
    - /bin/cp *.php $DEPLOYPATH #not sure if the wildcard would work buut we'll see
    - /bin/cp footer.php $DEPLOYPATH
    - /bin/find -type f -maxdepth 1 -exec /bin/cp {} $DEPLOYPATH \;