deployment:
  tasks:
    - export DEPLOYPATH=/home/kkaugcih/public_html
    - /bin/cp Front-end/index.html $DEPLOYPATH
    - /bin/cp Front-end/style.css $DEPLOYPATH
    - /bin/cp -r Front-end/img/. $DEPLOYPATH/img/
    - /bin/cp -r Front-end/Photos/. $DEPLOYPATH/Photos/
    - /bin/cp Front-end/index-2.html $DEPLOYPATH
    - /bin/cp Front-end/index-old.html $DEPLOYPATH
    - /bin/find Front-end -type f -maxdepth 1 -exec /bin/cp {} $DEPLOYPATH \;