deployment:
  tasks:
    - export DEPLOYPATH=/home/kkaugcih/public_html
    - /bin/cp Latest-Front-end/Home-index.html $DEPLOYPATH
    - /bin/cp Latest-Front-end/style.css $DEPLOYPATH
    - /bin/cp -r Latest-Front-end/Photos/. $DEPLOYPATH/Photos/
    - /bin/cp User-auth.php $DEPLOYPATH
    - /bin/cp User-functions.php $DEPLOYPATH
    - /bin/find Latest-Front-end -type f -maxdepth 1 -exec /bin/cp {} $DEPLOYPATH \;