deployment:
  tasks:
    - export DEPLOYPATH=/home/kkaugcih/public_html
    # - export REPOPATH=/home/kkaugcih/GarageWeb
    - /bin/cp Front-end/Home-index.html $DEPLOYPATH
    # - /bin/cp Front-end/*.html $DEPLOYPATH
    # - /bin/cp Front-end/*.css $DEPLOYPATH
    # - /bin/cp -r Front-end/Photos/. $DEPLOYPATH/Photos/
    # - /bin/cp -r Front-end/SvgFiles/. $DEPLOYPATH/SvgFiles/
    - /bin/cp User-auth.php $DEPLOYPATH
    - /bin/cp User-functions.php $DEPLOYPATH
    - /bin/find Front-end -type f -maxdepth 2 -exec /bin/cp {} $DEPLOYPATH \;