CREATE PROCEDURE AddProduct
    @PRODUCTNAME NVARCHAR(100),
    @PRODUCTDESC NVARCHAR(255),
    @PRICE DECIMAL(10, 2),
    @SOLD INT 
AS
BEGIN
    SET NOCOUNT ON;

    -- Insert a new product
    INSERT INTO Products ( PRODUCTNAME, PRODUCTDESC, PRICE, SOLD)
    VALUES (@PRODUCTNAME, @PRODUCTDESC, @PRICE, @SOLD);

    PRINT 'Product successfully added.';
END;