CREATE PROCEDURE AddPurchaseHistory
    @PURCHASEID NVARCHAR(50),
    @USERID NVARCHAR(50),
    @PRODUCTID NVARCHAR(50) = NULL,
    @SERVICEID NVARCHAR(50) = NULL,
    @PURCHASE_DATE DATETIME,
    @PAYMENT_METHOD NVARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;

    -- Insert a new purchase history record
    INSERT INTO PurchaseHistory (PURCHASEID, USERID, PRODUCTID, SERVICEID, PURCHASE_DATE, PAYMENT_METHOD)
    VALUES (@PURCHASEID, @USERID, @PRODUCTID, @SERVICEID, @PURCHASE_DATE, @PAYMENT_METHOD);

    PRINT 'Purchase successfully added.';
END;
