CREATE PROCEDURE AddProduct
    @PRODUCTID NVARCHAR(50),
    @PRODUCTNAME NVARCHAR(100),
    @PRODUCTDESC NVARCHAR(255),
    @PRICE DECIMAL(10, 2),
    @SOLD INT = 0
AS
BEGIN
    SET NOCOUNT ON;

    -- Insert a new product
    INSERT INTO Products (PRODUCTID, PRODUCTNAME, PRODUCTDESC, PRICE, SOLD)
    VALUES (@PRODUCTID, @PRODUCTNAME, @PRODUCTDESC, @PRICE, @SOLD);

    PRINT 'Product successfully added.';
END;
