CREATE PROCEDURE AddService
    @SERVICEID NVARCHAR(50),
    @SERVICENAME NVARCHAR(100),
    @SERVICEDESC NVARCHAR(255),
    @MINIMUMPRICE DECIMAL(10, 2)
AS
BEGIN
    SET NOCOUNT ON;

    -- Insert a new service
    INSERT INTO GarageServices (SERVICEID, SERVICENAME, SERVICEDESC, MINIMUMPRICE)
    VALUES (@SERVICEID, @SERVICENAME, @SERVICEDESC, @MINIMUMPRICE);

    PRINT 'Service successfully added.';
END;
